create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password varchar(255) not null,
    first_name varchar(255),
    last_name varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6)
);

create table if not exists user_profiles (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    nickname varchar(255),
    age_range varchar(255),
    experience varchar(255),
    sensitivity varchar(255),
    skin_type_guess varchar(255),
    concerns varchar(255) array,
    lifestyle_factors varchar(255) array,
    notif_pref varchar(255),
    skin_feel varchar(255),
    post_wash_feel varchar(255),
    main_goal varchar(255),
    product_fit_intent varchar(255),
    reaction_history varchar(255),
    current_routine varchar(255) array,
    recent_actives varchar(255) array,
    reminder_preferences varchar(255) array,
    gender varchar(255),
    is_pregnant boolean,
    conditions varchar(255) array,
    allergens varchar(255) array,
    is_onboarded boolean
);

create unique index if not exists idx_user_profiles_user_id_unique on user_profiles(user_id);

create table if not exists user_products (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    name varchar(255) not null,
    brand varchar(255) not null,
    category varchar(255) not null,
    time_of_day varchar(255) not null,
    image_url varchar(255),
    cutout_image_url varchar(255),
    description text,
    expiry_date varchar(255),
    active_ingredients varchar(255) array,
    is_favorite boolean,
    created_at timestamp(6),
    updated_at timestamp(6)
);

create index if not exists idx_user_products_user_id_created_at on user_products(user_id, created_at desc);
