create table if not exists assistant_messages (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    prompt text not null,
    intent_type varchar(32) not null,
    detected_issue varchar(255),
    ai_response text not null,
    created_at timestamp(6)
);

create index if not exists idx_assistant_messages_user_id_created_at on assistant_messages(user_id, created_at desc);
