create table if not exists skin_logs (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id),
    photo_url varchar(512),
    skin_feeling varchar(64),
    used_new_product boolean,
    user_note text,
    analysis_json text,
    dryness_level varchar(16),
    redness_level varchar(16),
    oiliness_level varchar(16),
    blemish_level varchar(16),
    irritation_level varchar(16),
    created_at timestamp(6)
);

create index if not exists idx_skin_logs_user_id_created_at on skin_logs(user_id, created_at desc);
